#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <cstdint>

struct OpcodeDef {
    std::string mnemonic;
    uint8_t code;
};

struct IRInstruction {
    std::string op;
    std::vector<std::string> args;
};

struct RoutineArtifact {
    std::string name;
    std::vector<IRInstruction> ir;
    std::vector<uint8_t> bytecode;
};

class Transpiler {
public:
    bool LoadConfig(const std::string& configPath) {
        std::ifstream in(configPath);
        if (!in) {
            return false;
        }

        std::string line;
        while (std::getline(in, line)) {
            line = Trim(line);
            if (line.empty() || line[0] == '#') {
                continue;
            }

            if (line.rfind("virtualize=", 0) == 0) {
                selectedFunctions.insert(Trim(line.substr(11)));
            }
        }

        return true;
    }

    void ProcessFile(const std::string& inputPath, const std::string& outputPath) {
        std::ifstream input(inputPath);
        std::ofstream output(outputPath);

        if (!input || !output) {
            std::cerr << "[!] Unable to open input/output files." << std::endl;
            return;
        }

        std::vector<std::string> lines;
        std::string line;
        while (std::getline(input, line)) {
            lines.push_back(line);
        }

        DetectSelectedFunctions(lines);
        EmitTransformedSource(lines, output);
        EmitProtectedSection(output);
    }

private:
    std::unordered_set<std::string> selectedFunctions;
    std::vector<RoutineArtifact> routines;
    std::vector<OpcodeDef> opcodeMap {
        {"PUSH_CONST", 0x01},
        {"ADD", 0x02},
        {"SUB", 0x03},
        {"XOR", 0x04},
        {"RET", 0x7F},
    };

    static std::string Trim(const std::string& v) {
        size_t s = 0, e = v.size();
        while (s < e && std::isspace(static_cast<unsigned char>(v[s]))) ++s;
        while (e > s && std::isspace(static_cast<unsigned char>(v[e - 1]))) --e;
        return v.substr(s, e - s);
    }

    void DetectSelectedFunctions(const std::vector<std::string>& lines) {
        std::regex fnRegex(R"((?:int|void|uint64_t|long)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\()") ;
        bool nextFunctionSelected = false;

        for (const auto& line : lines) {
            if (line.find("IRONLOCK_VM_FUNC") != std::string::npos) {
                nextFunctionSelected = true;
                continue;
            }

            std::smatch m;
            if (std::regex_search(line, m, fnRegex)) {
                std::string fn = m[1].str();
                if (nextFunctionSelected || selectedFunctions.count(fn)) {
                    selectedFunctions.insert(fn);
                }
                nextFunctionSelected = false;
            }
        }
    }

    void EmitTransformedSource(const std::vector<std::string>& lines, std::ofstream& out) {
        out << "// Generated by IronLock Transpiler (manifest-aware)\n";
        out << "#include \"IronLock/ProtectionSDK.h\"\n\n";

        std::regex fnRegex(R"((?:int|void|uint64_t|long)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\()") ;

        bool inSelectedFn = false;
        int braceDepth = 0;
        RoutineArtifact current;

        for (const auto& line : lines) {
            std::smatch m;
            if (!inSelectedFn && std::regex_search(line, m, fnRegex)) {
                std::string fn = m[1].str();
                if (selectedFunctions.count(fn)) {
                    inSelectedFn = true;
                    current = RoutineArtifact{};
                    current.name = fn;
                    out << line << "\n";
                    continue;
                }
            }

            if (inSelectedFn) {
                for (char c : line) {
                    if (c == '{') ++braceDepth;
                    if (c == '}') --braceDepth;
                }

                auto irLines = BuildIR(line);
                for (const auto& ir : irLines) {
                    current.ir.push_back(ir);
                }

                out << "    // [IronLock] virtualized: " << Trim(line) << "\n";

                if (braceDepth <= 0 && line.find('}') != std::string::npos) {
                    current.ir.push_back({"RET", {}});
                    current.bytecode = GenerateBytecode(current.ir);
                    routines.push_back(current);
                    inSelectedFn = false;
                    out << line << "\n";
                }
                continue;
            }

            out << line << "\n";
        }
    }

    std::vector<IRInstruction> BuildIR(const std::string& line) {
        std::vector<IRInstruction> ir;
        std::regex imm(R"((\d+))");
        for (auto it = std::sregex_iterator(line.begin(), line.end(), imm); it != std::sregex_iterator(); ++it) {
            ir.push_back({"PUSH_CONST", {(*it)[1].str()}});
        }

        if (line.find('+') != std::string::npos) ir.push_back({"ADD", {}});
        if (line.find('-') != std::string::npos) ir.push_back({"SUB", {}});
        if (line.find('^') != std::string::npos) ir.push_back({"XOR", {}});
        return ir;
    }

    std::vector<uint8_t> GenerateBytecode(const std::vector<IRInstruction>& ir) {
        std::unordered_map<std::string, uint8_t> op;
        for (const auto& def : opcodeMap) {
            op[def.mnemonic] = def.code;
        }

        std::vector<uint8_t> bc;
        for (const auto& inst : ir) {
            auto it = op.find(inst.op);
            if (it == op.end()) continue;
            bc.push_back(it->second);
            if (inst.op == "PUSH_CONST" && !inst.args.empty()) {
                uint32_t value = static_cast<uint32_t>(std::stoul(inst.args[0]));
                bc.push_back(static_cast<uint8_t>(value & 0xFF));
                bc.push_back(static_cast<uint8_t>((value >> 8) & 0xFF));
                bc.push_back(static_cast<uint8_t>((value >> 16) & 0xFF));
                bc.push_back(static_cast<uint8_t>((value >> 24) & 0xFF));
            }
        }
        return bc;
    }

    void EmitProtectedSection(std::ofstream& out) {
        out << "\n// -------- IronLock Protected Section --------\n";
        out << "static const unsigned char g_ironlock_protected_blob[] = {\n";

        for (const auto& routine : routines) {
            for (size_t i = 0; i < routine.bytecode.size(); ++i) {
                out << "0x" << std::hex << static_cast<int>(routine.bytecode[i]) << std::dec;
                if (i + 1 != routine.bytecode.size()) out << ", ";
            }
            out << ", // routine: " << routine.name << "\n";
        }

        out << "};\n\n";
        out << "// Metadata + opcode map for runtime VM dispatcher\n";
        out << "struct IronLockOpcodeMap { const char* name; unsigned char opcode; };\n";
        out << "static const IronLockOpcodeMap g_ironlock_opcodes[] = {\n";
        for (const auto& def : opcodeMap) {
            out << "    {\"" << def.mnemonic << "\", 0x" << std::hex << static_cast<int>(def.code) << std::dec << "},\n";
        }
        out << "};\n";

        out << "// Relocation patch hints for compiler/main.cpp manifest-driven patching\n";
        out << "// format: routine_name, callsite_rva, vm_stub_rva\n";
        for (const auto& routine : routines) {
            out << "// patch," << routine.name << ",0x0,0x0\n";
        }
    }
};

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cout << "IronLock Transpiler\nUsage: iltranspiler <input.cpp> <output.cpp> [config.ilvm]" << std::endl;
        return 1;
    }

    Transpiler transpiler;
    if (argc >= 4) {
        transpiler.LoadConfig(argv[3]);
    }

    transpiler.ProcessFile(argv[1], argv[2]);
    std::cout << "[+] IronLock Transpiler: processed " << argv[1] << " -> " << argv[2] << std::endl;
    return 0;
}
