#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <regex>

// IronLock Transpiler v1.0
// Functional parser for C++ to IronLock Bytecode

class Transpiler {
public:
    void ProcessFile(const std::string& inputPath, const std::string& outputPath) {
        std::ifstream input(inputPath);
        std::ofstream output(outputPath);
        std::string line;
        bool inProtectBlock = false;

        output << "// Generated by IronLock Transpiler\n";
        output << "#include \"IronLock/ProtectionSDK.h\"\n";

        while (std::getline(input, line)) {
            if (line.find("IRONLOCK_VM_START") != std::string::npos) {
                inProtectBlock = true;
                output << "[]() {\n    VM_START\n";
                continue;
            }
            if (line.find("IRONLOCK_VM_END") != std::string::npos) {
                inProtectBlock = false;
                output << "    VM_RET\n    VM_END\n}();\n";
                continue;
            }

            if (inProtectBlock) {
                // Handle basic assignments like 'int x = 10 + 20;'
                std::smatch match;
                std::regex valRegex("([0-9]+)");
                auto words_begin = std::sregex_iterator(line.begin(), line.end(), valRegex);
                auto words_end = std::sregex_iterator();

                for (std::sregex_iterator i = words_begin; i != words_end; ++i) {
                    output << "    VM_PUSH(" << (*i).str() << ")\n";
                }

                if (line.find("+") != std::string::npos) output << "    VM_ADD\n";
                if (line.find("-") != std::string::npos) output << "    VM_SUB\n";
                if (line.find("^") != std::string::npos) output << "    VM_XOR\n";
            } else {
                output << line << "\n";
            }
        }
    }
};

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cout << "IronLock Transpiler v1.0" << std::endl;
        std::cout << "Usage: iltranspiler <src.cpp> <out.cpp>" << std::endl;
        return 1;
    }
    Transpiler t;
    t.ProcessFile(argv[1], argv[2]);
    return 0;
}
